### ISSUE TITLE
Bedroom: Stuck Animation/Leaving room on action in room.

### ISSUE THREAD

**Issue by KoriAquilina3** [AIESydneyStudents/HEXAD_GAMES#31]
Just as in the GYM room when doing the dumbbells exercise the shootout bar gets roomed which stops the player from breaking the action and animation if this same feature is added to the bedroom it would stop the player from breaking the mini game and getting into bed animations.

**Comment by firstomars** [comment]
@KoriAquilina3 hey I've deactivated main flyout button while eat animation and minigame animation plays. Give it a test when you have a sec. We'll need to keep the main flyout button active when sleeping, as we'll need it to change time for playtesting purposes.
